title: Coder-Coding-The-Code
#description: Cayman is a clean, responsive theme for GitHub Pages.
#show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

deploy:
  type: git
  repo: git@github.com:coder-coding-the-code/coder-coding-the-code.github.io.git
  branch: blog
